language: python
python: "2.7"
sudo: required
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenblas-base
      - libopenblas-dev
before_install: "pip install scipy"
install: "pip install ."
script: pygraphc